package com.liujc.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liujc.greendao.Bean.LTest;
import com.liujc.greendao.Bean.Profession;
import com.liujc.greendao.Bean.User;

import com.liujc.greendao.dao.LTestDao;
import com.liujc.greendao.dao.ProfessionDao;
import com.liujc.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lTestDaoConfig;
    private final DaoConfig professionDaoConfig;
    private final DaoConfig userDaoConfig;

    private final LTestDao lTestDao;
    private final ProfessionDao professionDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lTestDaoConfig = daoConfigMap.get(LTestDao.class).clone();
        lTestDaoConfig.initIdentityScope(type);

        professionDaoConfig = daoConfigMap.get(ProfessionDao.class).clone();
        professionDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        lTestDao = new LTestDao(lTestDaoConfig, this);
        professionDao = new ProfessionDao(professionDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(LTest.class, lTestDao);
        registerDao(Profession.class, professionDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        lTestDaoConfig.clearIdentityScope();
        professionDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public LTestDao getLTestDao() {
        return lTestDao;
    }

    public ProfessionDao getProfessionDao() {
        return professionDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
