package com.liujc.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.liujc.greendao.Bean.Profession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROFESSION".
*/
public class ProfessionDao extends AbstractDao<Profession, Long> {

    public static final String TABLENAME = "PROFESSION";

    /**
     * Properties of entity Profession.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Major = new Property(1, String.class, "major", false, "MAJOR");
        public final static Property College = new Property(2, String.class, "college", false, "COLLEGE");
    }


    public ProfessionDao(DaoConfig config) {
        super(config);
    }
    
    public ProfessionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROFESSION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MAJOR\" TEXT," + // 1: major
                "\"COLLEGE\" TEXT);"); // 2: college
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROFESSION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Profession entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String major = entity.getMajor();
        if (major != null) {
            stmt.bindString(2, major);
        }
 
        String college = entity.getCollege();
        if (college != null) {
            stmt.bindString(3, college);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Profession entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String major = entity.getMajor();
        if (major != null) {
            stmt.bindString(2, major);
        }
 
        String college = entity.getCollege();
        if (college != null) {
            stmt.bindString(3, college);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Profession readEntity(Cursor cursor, int offset) {
        Profession entity = new Profession( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // major
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // college
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Profession entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMajor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCollege(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Profession entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Profession entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Profession entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
